on: push
name: rustfmt check

jobs:
  rustfmt_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Build
        run: cargo build
      - name: Run rustfmt
        run: cargo fmt --all -- --check
